apiVersion: v1
kind: Pod
metadata:
  name: app-demo
  namespace: default
  labels:
    app: app-demo
spec:
  containers:
  - name: app-demo
    image: tonnytg/app-demo:v0.1.0
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
